// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2sXvFDcluP6Yu-TQgQ7cqszXz7hDw6n0',
    appId: '1:360859480414:web:a7bae58c8862c655f45fcf',
    messagingSenderId: '360859480414',
    projectId: 'mobile-lab-flutter-fireb-f03f7',
    authDomain: 'mobile-lab-flutter-fireb-f03f7.firebaseapp.com',
    storageBucket: 'mobile-lab-flutter-fireb-f03f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJE91AL1eKT5BUX9DZD53dqlr1vhyXlpw',
    appId: '1:360859480414:android:94ec09fe04cce91ff45fcf',
    messagingSenderId: '360859480414',
    projectId: 'mobile-lab-flutter-fireb-f03f7',
    storageBucket: 'mobile-lab-flutter-fireb-f03f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnI1FXq-qnMYzWUqVqFhER9cOLMpb60xI',
    appId: '1:360859480414:ios:c9bfc7ff2a9940faf45fcf',
    messagingSenderId: '360859480414',
    projectId: 'mobile-lab-flutter-fireb-f03f7',
    storageBucket: 'mobile-lab-flutter-fireb-f03f7.appspot.com',
    iosClientId: '360859480414-kj6kev7paton35rh618q1d6n27ees5s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnI1FXq-qnMYzWUqVqFhER9cOLMpb60xI',
    appId: '1:360859480414:ios:c9bfc7ff2a9940faf45fcf',
    messagingSenderId: '360859480414',
    projectId: 'mobile-lab-flutter-fireb-f03f7',
    storageBucket: 'mobile-lab-flutter-fireb-f03f7.appspot.com',
    iosClientId: '360859480414-kj6kev7paton35rh618q1d6n27ees5s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase01',
  );
}
